### ISSUE TITLE
How convert data  from fingerprint?

### ISSUE THREAD

**Issue by jpatryk** [sparkfun/Fingerprint_Scanner-TTL#22]
Hi, 
this is possible or how i can format fingerprint scan to another format which i can send to another pc and check in database.

**Comment by bboyho** [comment]
Hi jpatryk,

It depends on the fingerprint device that you are using. I would assume that ADH Tech's fingerprint scanner has a specific format that is used. Checking the datasheet, it looks like each template is saved as a "*.dat" file but I am not sure if it is a standard format used by all fingerprint scanners. The GT-511C3 and GT511C1R have different sized templates so I do not think that they can use same fingerprint template files between each model.

Theoretically, it can be possible to use some sort of database online if you are using the same fingerprint models on remote computers. I do not have the specific details on accomplishing this task. Assuming the fingerprints are enrolled and saved in the server, you would probably need to write additional code that is able to download the template/database file from a server, save the template/database file to the local fingerprint scanner, identify the template based on the saved template/database, set a flag to indicate whether or note the fingerprint is valid, and then remove the template/database from the local fingerprint scanner until the next scan. Depending on the size of your database and how you handle the files, you may only need to download and remove the template/database if the template/database is updated on the server side. 

There appears to be an article that uses the GT-511C1R with a Raspberry Pi as a server and SQLite [ [FingerScanner: Embedding a Fingerprint Scanner in a Raspberry Pi](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4801596/) ]. Based on this information, it’s possible to have remote management of a database on multiple fingerprint scanners from a server.
