### ISSUE TITLE
Library didn't work on Arduino 101

### ISSUE THREAD

**Issue by bhavinpmakasana** [sparkfun/Fingerprint_Scanner-TTL#38]
The library is not working while compiling on Arduino 101. It gives an error ‘ErrorErrors_Enum’ does not name a type on line static ErrorErrors_Enum ParseFromBytes(byte high, byte low); 
Can you please check?

**Comment by bboyho** [comment]
Hawley's Arduino library was written on the Atmega328P with the Arduino Uno bootloader. The FPS_GT511C3 library may not work for all microcontrollers using the Arduino IDE. As you move away from the ATmega328P family, you may need to modify the code or port the library over to get it working. Unfortunately, the FPS_GT511C3 library is not supported for the Intel Curie on the Arduino 101.

While redundant, it would be easier and faster to just have an Atmega328P bootloaded with Arduino to handle the FPS code. To use the fingerprint scanner, you could just write additional code to have the ATmega328P send serial data to the other microcontroller.
