### ISSUE TITLE
Arduino nano problem

### ISSUE THREAD

**Issue by andrea080690** [sparkfun/Fingerprint_Scanner-TTL#41]
Hi, do you have some problem using arduino nano?
I have used arduino uno without problem but using arduino nano I have lots of warning and even if using the program SDK_DEMO like it save finger, when I try to use them it doesn't works.
Using this code:
`#include <SoftwareSerial.h>
#include "FPS_GT511C3.h"
#include "Arduino.h"
#include "Servo.h"

// need a serial port to communicate with the GT-511C3
SoftwareSerial gtSerial(8, 7); // Arduino RX (GT TX), Arduino TX (GT RX)
// the Arduino TX pin needs a voltage divider, see wiring diagram at:
// http://startingelectronics.com/articles/GT-511C3-fingerprint-scanner-hardware/

void setup() {
  Serial.begin(9600);    // serial connection to processing app.
  gtSerial.begin(9600);  // for communicating with the GT-511C3
}

byte rx_byte = 0;        // stores received byte

void loop() {
  if (Serial.available()) {
    // get byte from processing app. and send to FPS
    rx_byte = Serial.read();
    gtSerial.write(rx_byte);
  }
  // check for a byte from the GT-511C3
  if (gtSerial.available()) {
    // get a byte from the FPS and send it to the processing app.
    rx_byte = gtSerial.read();
    Serial.write(rx_byte);
  }
}`

These are the warning:

`sketch\FPS_GT511C3.cpp:9:25: warning: extra tokens at end of #include directive

 #include "FPS_GT511C3.h";

                         ^

In file included from sketch\FPS_GT511C3.cpp:9:0:

sketch\FPS_GT511C3.h:12:21: warning: extra tokens at end of #include directive

 #include "Arduino.h";

                     ^

In file included from sketch\FPS_GT511C3.cpp:9:0:

sketch\FPS_GT511C3.h:13:28: warning: extra tokens at end of #include directive

 #include "SoftwareSerial.h";

                            ^

sketch\FPS_GT511C3.cpp: In constructor 'Response_Packet::Response_Packet(byte*, bool)':

sketch\FPS_GT511C3.cpp:89:108: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[0], COMMAND_START_CODE_1, COMMAND_START_CODE_1, "COMMAND_START_CODE_1", UseSerialDebug);

                                                                                                            ^

sketch\FPS_GT511C3.cpp:90:108: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[1], COMMAND_START_CODE_2, COMMAND_START_CODE_2, "COMMAND_START_CODE_2", UseSerialDebug);

                                                                                                            ^

sketch\FPS_GT511C3.cpp:91:105: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[2], COMMAND_DEVICE_ID_1, COMMAND_DEVICE_ID_1, "COMMAND_DEVICE_ID_1", UseSerialDebug);

                                                                                                         ^

sketch\FPS_GT511C3.cpp:92:105: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[3], COMMAND_DEVICE_ID_2, COMMAND_DEVICE_ID_2, "COMMAND_DEVICE_ID_2", UseSerialDebug);

                                                                                                         ^

sketch\FPS_GT511C3.cpp:93:66: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[8], 0x30, 0x31, "AckNak_LOW", UseSerialDebug);

                                                                  ^

sketch\FPS_GT511C3.cpp:95:67: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[9], 0x00, 0x00, "AckNak_HIGH", UseSerialDebug);

                                                                   ^

sketch\FPS_GT511C3.cpp:100:85: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[10], checksum_low, checksum_low, "Checksum_LOW", UseSerialDebug);

                                                                                     ^

sketch\FPS_GT511C3.cpp:101:88: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

  CheckParsing(buffer[11], checksum_high, checksum_high, "Checksum_HIGH", UseSerialDebug);

                                                                                        ^

In file included from C:\Users\Andrea\Documents\Arduino\salva_impronta_nano\salva_impronta_nano.ino:18:0:

sketch\FPS_GT511C3.h:12:21: warning: extra tokens at end of #include directive

 #include "Arduino.h";

                     ^

In file included from C:\Users\Andrea\Documents\Arduino\salva_impronta_nano\salva_impronta_nano.ino:18:0:

sketch\FPS_GT511C3.h:13:28: warning: extra tokens at end of #include directive

 #include "SoftwareSerial.h";`

**Comment by bboyho** [comment]
Hi @andrea080690 ,

**Warnings**

Usually Arduino compile warnings can be ignored. This was brought up in the Arduino.cc forums [ [https://forum.arduino.cc/index.php?topic=474669.0](https://forum.arduino.cc/index.php?topic=474669.0) .

**Microcontroller Compatibility**

Hawley's Arduino library was written for the Arduino Uno with the Atmega328P. The FPS_GT511C3 library may not work for all microcontrollers using the Arduino IDE. As you move away from the ATmega328P family, you may need to modify the code or port the library over to get it working. I have not tried using the GT-511C3 with the [Arduino Nano](https://store.arduino.cc/usa/arduino-nano), but it looks like it should work. The Arduino Nano uses an Atmega328P and it is using 5V logic like the Arduino Uno.

**Troubleshooting**

If your code was working with the Arduino Uno, I recommend checking your connections and make sure there are no wires loose with the Arduino Nano. Also, your code is a bit different compared to the examples listed in the library. Try testing the basic examples.

If you are trying to use the SDK_DEMO.exe for the fingerprint scanner, you need to use a serial passthrough code [like this code used for SparkFun's XBee Shield => [https://learn.sparkfun.com/tutorials/xbee-shield-hookup-guide#example-communication-test](https://learn.sparkfun.com/tutorials/xbee-shield-hookup-guide#example-communication-test) ]. While the code was written for the XBee Shield, it should work with the fingerprint scanner and SDK_Demo.exe. The code just passes serial data to your computer's COM port. The software serial object is created as the XBee but that should not matter. If you use this example code, make sure to connect to the respective software serial pins on pin 2 and 3. The _FPS_Blink.ino_, _FPS_Enroll.ino_, and _FPS_IDFinger.ino_ were not designed to communicate with SDK_DEMO.exe.
