### ISSUE TITLE
Help with driver for ESP FreeRTOS

### ISSUE THREAD

**Issue by aarush22** [sparkfun/Fingerprint_Scanner-TTL#43]
Hi, I want to use this sensor with a ESP8266 and FreeRTOS env, since I couldn't find a driver for that, I was trying to build one myself. But I am not able to communicate with the fps using UART, I tried using the ```uart_putc()``` and ```uart_getc()``` functions for serial communication, but I am not receiving any response for the Open Command packet. I am writing the 12 byte Command packet, byte by byte using ```uart_putc()```, (which is a blocking function) and then I keep waiting for the response using ```uart_getc()``` but no response is received. Am I missing something?

**Comment by JoshHawley** [comment]
Probably the fact that there is no flow control. Your message may be waiting for a response from the scanner telling it that it is ok to send the next byte or something similar. Try to configure it to send the whole command packet at once.
