### ISSUE TITLE
Library option for FingerPrint ID delete, manual ID input - Finger print for scalable application

### ISSUE THREAD

**Issue by bidyutper** [sparkfun/Fingerprint_Scanner-TTL#52]
Didn't find any way to delete a particular id after enrolled. Also looking for Manual ID input via serial read in arduino while enrolling finger print. Plz need help. using Fingerprint Scanner - TTL (GT-521F32).

**Comment by JoshHawley** [comment]
If you look in the .h file you will find this line:
bool DeleteID(int ID);

also:
int EnrollStart(int id);

**Comment by bidyutper** [comment]
thx :)
