### ISSUE TITLE
Fast fingerprint scan via different baud rate

### ISSUE THREAD

**Issue by bidyutper** [sparkfun/Fingerprint_Scanner-TTL#55]
Can I change the baud rate to get results out of 1:N of 3000 database faster. Like if I want to change to 115200 baud rate?Also how to display fingerprint id out put to 16*2 LCD with fast scan enable no delay ....as refresh rate of LCD is poor not able to display with out delay which causes slow scan of fingerprint.

**Comment by bidyutper** [comment]
Also how to display fingerprint id out put to 16*2 LCD with fast scan enable no delay ....as refresh rate of LCD is poor not able to display with out delay which causes slow scan of fingerprint.

**Comment by JoshHawley** [comment]
While the scanner itself I worked with (and most scanners) can support 115200, you may run into issues with trying to accept the data that fast. IIRC the scanner does not have much in the way of flow control either. 

For your LCD problem (not much information provided, so taking a stab in the dark) it sounds like you might want it to have its own micro controller, then you just send the data, and let the other micro controller worry about the refresh rates. Something like this: https://www.sparkfun.com/products/9395

**Comment by bidyutper** [comment]
OK..thx for ur input.
I will change the .cpp file 
`FPS_GT511C3::FPS_GT511C3(uint8_t rx, uint8_t tx)
	: _serial(rx,tx)
{
	pin_RX = rx;
	pin_TX = tx;
	_serial.begin(9600);
	this->UseSerialDebug = false;
};
`
Here `_serial.begin(9600);` to `115200` and checkout.

**Comment by bboyho** [comment]
It appears that your question has been answered. I am closing the issue out. It also looks like Fasgort has added some improvements to the library through pull request commits.
