### ISSUE TITLE
How would I code it in C ?

### ISSUE THREAD

**Issue by arongauti1** [sparkfun/Fingerprint_Scanner-TTL#59]
Hi, I want to chance my Arduino code for a Fingerprint scanner TTL (GT-521F32) to a C code.

 

Can anyone help me? 

https://www.sparkfun.com/product...

Hi, I have enrolled in my fingerprint. 

I only need to Verify / Identify one/two fingerprints.

 

I also have a UART.c and UART.h and delay.h-.c

 

And in the Fingerprint.pdf there is what I want to accomplish.

and the circuit in finger.jpg

 

The fingerprint .h

/*
 * fingerprint.h
 *
 *  Created on: 16. mar. 2019
 *      Author: Aron Gauti
 */

#ifndef FINGERPRINT_H_
#define FINGERPRINT_H_

void Open();
char SetLED(char b);
char IsPressFinger(char b);
char CaptureFinger(char highquality);
int Identify();

#endif /* FINGERPRINT_H_ */
 

 

 

fingerprint.c

 

/*
 * fingerprint.c
 *
 *  Created on: 16. mar. 2019
 *      Author: Aron Gauti
 */

#include <avr/io.h>
#include <avr/interrupt.h>

//Initialises the device and gets ready for commands
void Open()
{
    char arr[4];// Bý  til 4x fylki með UART, fullt af núllum

    // Finna fjöldi GetPacketBytes()
    // SendCommand(,) sendir
    // Fá response

}

// Turns on or off the LED backlight
    // LED must be on to see fingerprints
    // Parameter: true turns on the backlight, false turns it off
    // Returns: True if successful, false if not
char SetLED(char b) //bool fall
{

}

// Checks to see if a finger is pressed on the FPS
// Return: true if finger pressed, false if not
char IsPressFinger(char b)
{

}

// Captures the currently pressed finger into onboard ram
// Parameter: true for high quality image(slower), false for low quality image (faster)
// Generally, use high quality for enrollment, and low quality for verification/identification
// Returns: True if ok, false if no finger pressed
char CaptureFinger(char highquality)
{

}

// Checks the currently pressed finger against all enrolled fingerprints
// Returns:
//    Verified against the specified ID (found, and here is the ID number)
    //           0-199, if using GT-521F32/GT-511C3
    //      Failed to find the fingerprint in the database
    //           200, if using GT-521F32/GT-511C3
int Identify()
{

}

**Comment by arongauti1** [comment]
https://www.avrfreaks.net/forum/code-fingerprint-scanner-c#comment-2659646,

**Comment by loricrotser** [comment]
Hello! Did you end up getting this sorted out? From the initial request, it sounds like you are looking for technical assistance; the github issues are used primarily for bugs and pull requests related to the libraries or pcbs. If you still need help, feel free to visit our [forums](https://forum.sparkfun.com/index.php) and we'll see what we can do to help you out. Thank you!
