### ISSUE TITLE
Library for GT-521F32

### ISSUE THREAD

**Issue by sivabharaniii** [sparkfun/Fingerprint_Scanner-TTL#61]
Hi,
    I am working with GT-521F32,in that librarie some functions are not implemented due to memory restrictions on arduino.
I need those libraries to be implemented,I am using Arduino mega 2560 with in built wifi board which has more memory than arduino uno.
Functions to be implemented in libarary
1) GET IMAGE()
2) GET RAW IMAGE()
3) GET TEMPLATE ()
4)SET TEMPLATE()

**Comment by brianrho** [comment]
My [library](https://github.com/brianrho/GT5X) implements these already if you're still interested.

**Comment by bboyho** [comment]
Hi,

It looks like your question has been answered so I will be closing this out. There is a [pull request](https://github.com/sparkfun/Fingerprint_Scanner-TTL/pull/54) that implements those features and it looks like JoshHawley briefly reviewed it. However, I have not tested it out. It looks like brianrho has implemented those features with additional examples. ;)
