### ISSUE TITLE
FPS_Blink not working

### ISSUE THREAD

**Issue by tiggbigms252** [sparkfun/Fingerprint_Scanner-TTL#62]
I am using the Fingerprint Scanner with a 5V Arduino pro mini. I have it hooked up the way the hookup guide tells me. I have tried several different pin numbers for the Rx and Tx, and none of them do anything. When I look in the serial monitor, it says that it sends the open command and then one serial command, and then nothing else happens. The fingerprint scanner just sits there. There are no lights turning on at all, no LEDs blinking or anything. I even bought a new scanner to see if that was the problem, to no avail.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. If you have not already, I would [check your connections](https://learn.sparkfun.com/tutorials/sparkfun-troubleshooting-tips#hardware-checks).  The Pro Mini requires you to solder headers to the development board. You can have issues with the connection if the solder joint is bad or there is water soluble flux residue. The image linked in the troubleshooting tutorial shows the board connected to a 3.3V so make sure that you are using a logic level converter. Also, make sure that the solder joints are sufficient on the converter as well. Make sure to check your wires ensure that they secure and on the correct connector side. The LED on the back of the fingerprint scanner.

If you are still having problems, I recommend checking with with our [technical assistance](https://www.sparkfun.com/technical_assistance) for the best support
